FROM python:3.11.7-bookworm

RUN mkdir -p /app
COPY . /app
WORKDIR /app

RUN pip install -r requirements_dev.txt

EXPOSE 8000

#The manage.py command gives you a nice dev environment,
#but you may want to temporarily switch to gunicorn if you need to debug server problems on live
#CMD gunicorn --bind 0.0.0.0:8000 djangoproject.wsgi:application
CMD python manage.py runserver 0.0.0.0:8000
