"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import json
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "jsondataferret.apps.JsondataferretConfig",
    "indigo.apps.IndigoConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoproject.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

LOGIN_REDIRECT_URL = "/app/"

# We disable MemoryFileUploadHandler - there is code in app that assumes all files are written to disk
FILE_UPLOAD_HANDLERS = ["django.core.files.uploadhandler.TemporaryFileUploadHandler"]

JSONDATAFERRET_SPREADSHEET_FORM_DATE_FORMAT = "%Y-%m-%d"


with open(os.path.join(BASE_DIR, "indigo", "jsonschema", "project.json")) as fp:
    project_json_schema = json.load(fp)


with open(os.path.join(BASE_DIR, "indigo", "jsonschema", "organisation.json")) as fp:
    organisation_json_schema = json.load(fp)


JSONDATAFERRET_TYPE_INFORMATION = {
    "project": {
        "json_schema": project_json_schema,
        "spreadsheet_form_guide": os.path.join(
            BASE_DIR, "indigo", "spreadsheetform_guides", "project.xlsx",
        ),
        "fields": [
            {"key": "/status", "title": "Status"},
            {"key": "/name/value", "title": "Name"},
            {"key": "/alternative_names/value", "title": "Alternative Names"},
            {"key": "/stage_development/value", "title": "Stage of Development"},
            {
                "key": "/stage_development/source_ids",
                "title": "Stage of Development (Sources)",
            },
            {
                "key": "/stage_development/status",
                "title": "Stage of Development (Status)",
            },
            # dates group
            {
                "key": "/dates/outcomes_contract_signed/value",
                "title": "Date outcomes contract signed",
            },
            {
                "key": "/dates/outcomes_contract_signed/status",
                "title": "Date outcomes contract signed (Status)",
            },
            {
                "key": "/dates/contracts_between_all_parties_signed/value",
                "title": "Date contracts between all parties signed",
            },
            {
                "key": "/dates/contracts_between_all_parties_signed/status",
                "title": "Date contracts between all parties signed (Status)",
            },
            {
                "key": "/dates/anticipated_completion_date/value",
                "title": "Anticipated completion date",
            },
            {
                "key": "/dates/anticipated_completion_date/status",
                "title": "Anticipated completion date (Status)",
            },
            {
                "key": "/dates/actual_completion_date/value",
                "title": "Actual completion date",
            },
            {
                "key": "/dates/actual_completion_date/status",
                "title": "Actual completion date (Status)",
            },
            {
                "key": "/dates/start_date_of_service_provision/value",
                "title": "Start date of service provision",
            },
            {
                "key": "/dates/start_date_of_service_provision/status",
                "title": "Start date of service provision (Status)",
            },
            {
                "key": "/dates/anticipated_end_date_of_service_provision/value",
                "title": "Anticipated end date of service provision",
            },
            {
                "key": "/dates/anticipated_end_date_of_service_provision/status",
                "title": "Anticipated end date of service provision (Status)",
            },
            {
                "key": "/dates/actual_end_date_of_service_provision/value",
                "title": "Actual end date of service provision",
            },
            {
                "key": "/dates/actual_end_date_of_service_provision/status",
                "title": "Actual end date of service provision (Status)",
            },
            {"key": "/dates/source_ids", "title": "Dates (Sources)"},
            {"key": "/dates/notes", "title": "Notes (Sources)"},
            # Overall project finance
            # TODO
            # Purpose and classifications
            # TODO
            # Service and beneficiaries
            # TODO
            # Changes to project due to COVID-19
            # TODO
            # Outcome Funds
            {
                "type": "list",
                "key": "/outcome_funds",
                "title": "Outcome Funds",
                "fields": [
                    {"key": "/id", "title": "ID"},
                    {"key": "/name", "title": "Name"},
                    {"key": "/identifier_scheme", "title": "Identifier_scheme"},
                    {"key": "/identifier", "title": "Identifier"},
                    {"key": "/organisation_ids", "title": "Organisations"},
                    {"key": "/country", "title": "Country"},
                    {"key": "/source_ids", "title": "Sources"},
                    {"key": "/notes", "title": "Notes"},
                    {"key": "/status", "title": "Status"},
                ],
            },
            # Delivery Locations
            # TODO
            # Sources
            # TODO
            # Organisations
            # TODO
            # Service Provisions
            # TODO
            # Outcome Payment Comitments
            # TODO
            # Investements
            # TODO
            # Intermediary services
            # TODO
            # Outcome Metrics
            # TODO
            # Results
            # TODO
            # Open Contracting
            # TODO
            # 360Giving
            # TODO
        ],
    },
    "organisation": {
        "json_schema": organisation_json_schema,
        "spreadsheet_form_guide": os.path.join(
            BASE_DIR, "indigo", "spreadsheetform_guides", "organisation.xlsx",
        ),
        "fields": [
            {"key": "/org-ids/company/value", "title": "ORG-Ids - company"},
            {"key": "/org-ids/charity/value", "title": "ORG-Ids - charity"},
            {"key": "/org-ids/other/value", "title": "ORG-Ids - other"},
            {"key": "/contact/name/value", "title": "Contact Name"},
            {"key": "/contact/email/value", "title": "Contact Email"},
            {"key": "/website/value", "title": "Website"},
            {"key": "/address/value", "title": "Address"},
            {"key": "/postcode/value", "title": "Postcode"},
            {"key": "/country/value", "title": "Country"},
        ],
    },
}


if "ON_HEROKU" in os.environ:
    import django_heroku

    django_heroku.settings(locals())
    DEBUG = False


else:

    import environ

    env = environ.Env(  # set default values and casting
        # SECURITY WARNING: keep the secret key used in production secret!
        JSONDATAFERRET_SECRET_KEY=(
            str,
            "lz@kp-&z6grz#fp#*!mi6c4-mozm)1u6m$57j%v21#u9l#lnog",
        ),
        JSONDATAFERRET_DEBUG=(bool, True),
        JSONDATAFERRET_ALLOWED_HOSTS=(list, []),
        JSONDATAFERRET_DATABASE_NAME=(str, "app"),
        JSONDATAFERRET_DATABASE_USER=(str, "app"),
        JSONDATAFERRET_DATABASE_PASSWORD=(str, "password"),
        JSONDATAFERRET_DATABASE_HOST=(str, "localhost"),
    )

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = env("JSONDATAFERRET_SECRET_KEY")

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = env("JSONDATAFERRET_DEBUG")

    ALLOWED_HOSTS = env("JSONDATAFERRET_ALLOWED_HOSTS")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("JSONDATAFERRET_DATABASE_NAME"),
            "USER": env("JSONDATAFERRET_DATABASE_USER"),
            "PASSWORD": env("JSONDATAFERRET_DATABASE_PASSWORD"),
            "HOST": env("JSONDATAFERRET_DATABASE_HOST"),
        }
    }
