# Generated by Django 3.0.6 on 2020-05-29 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=200, unique=True)),
                ("exists", models.BooleanField(default=False)),
                ("status_public", models.BooleanField(default=False)),
                (
                    "data_public",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "data_private",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
        ),
    ]
