# Generated by Django 3.0.7 on 2020-06-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondataferret", "0002_jsondataferret"),
        ("indigo", "0005_projectincludesorganisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jsondataferret.Record",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jsondataferret.Record",
            ),
        ),
    ]
