# Generated by Django 3.0.7 on 2020-07-03 14:28

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondataferret", "0002_jsondataferret"),
        ("indigo", "0006_auto_20200610_1608"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=200, unique=True)),
                ("exists", models.BooleanField(default=False)),
                ("status_public", models.BooleanField(default=False)),
                (
                    "data_public",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "data_private",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jsondataferret.Record",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProjectIncludesFund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_current_data", models.BooleanField(default=False)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="included_by_projects",
                        to="indigo.Fund",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="includes_funds",
                        to="indigo.Project",
                    ),
                ),
            ],
            options={"unique_together": {("project", "fund")},},
        ),
    ]
