# Generated by Django 3.1 on 2020-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indigo", "0007_fund_projectincludesfund"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="full_text_search_private",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="organisation",
            name="full_text_search_private",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="full_text_search_private",
            field=models.TextField(default=""),
        ),
    ]
