# Generated by Django 3.1 on 2020-09-11 17:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indigo", "0009_project_social_investment_prototype"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimport",
            name="exception",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectimport",
            name="file_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectimport",
            name="file_not_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectimport",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
