# Generated by Django 3.1 on 2021-01-27 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indigo", "0010_auto_20200911_1707"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_quality_report_counts_by_priority",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
