# Generated by Django 3.2.12 on 2022-05-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indigo", "0014_pipeline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indigo",
            options={
                "managed": False,
                "permissions": (
                    ("admin", "Admin - All admin tasks on Indigo data"),
                    (
                        "data_steward",
                        "Data Steward - View all Indigo data, submit edits for moderation, can make private/disputed",
                    ),
                ),
            },
        ),
    ]
