# Generated by Django 3.2.17 on 2023-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jsondataferret", "0004_auto_20220603_0827"),
        ("indigo", "0017_pipelineimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoiningUpInitiative",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=200, unique=True)),
                ("exists", models.BooleanField(default=False)),
                ("status_public", models.BooleanField(default=False)),
                ("data_public", models.JSONField(default=dict)),
                ("data_private", models.JSONField(default=dict)),
                ("data_sandboxes", models.JSONField(default=dict)),
                ("full_text_search_private", models.TextField(default="")),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="jsondataferret.record",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
